### PR TITLE
Feature/should be able to view profile

### PR DESCRIPTION
**Pull request by tiedye93**

### CODE REVIEW

**Comment by tiedye93** [comment]
Changed the feature to just viewing the profile

**Comment by tiedye93** [comment]
Only thing to add here is to change the request to the profile service. Still have it connected to SWAPI.

**Comment by jaimejgonzalez1** [comment]
Let's group up on Monday, and figure out how to keep each branch similar at the app level

**Comment by tiedye93** [comment]
Ready for review. Removed all files that should limit merge conflicts

**Pull request merged**
